### ISSUE TITLE
pyjmad and SWAN

### ISSUE THREAD

**Issue by sterbini** [pymad/pyjmad#6]
Hi,

can pyjmad be used from CERN SWAN?
Thanks,
G.

**Comment by michi42** [comment]
Hi Guido,

I just gave it a try - from the python or jmad side there is no problem, it can be installed with pip --user as usual.

But unfortunately the madx version we use in jmad does not work on SWAN/Docker (32bit vs 64bit problem). I'll make an update to JMad to include a version which also works on SWAN soon.

Cheers,
Michi
